galaxy_info:
  role_name: perfmon_install
  author: Arun Gopinath
  description: Installs Erik Darling's PerformanceMonitor on SQL Server instances via sqlcmd
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions: all
    - name: Debian
      versions: all
    - name: Windows
      versions: all

dependencies: []
