---
all:
  children:
    sql_servers:
      hosts:
        sql2022:
          ansible_host: localhost
          ansible_connection: local
          mssql_port: 14333
          ds_host: mssql-2022
          ds_port: 1433
        sql2025:
          ansible_host: localhost
          ansible_connection: local
          mssql_port: 14334
          ds_host: mssql-2025
          ds_port: 1433

    grafana:
      hosts:
        grafana:
          ansible_host: localhost
          ansible_connection: local
          grafana_url: http://localhost:3000
